# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

<<<<<<< HEAD
client_id = "d8508b1cc390b4f6c1d3f9c6bf6f0d12"
name = "Sticky_Cart_Bar"
handle = "sticky_cart_bar-1"
application_url = "https://suspended-suzuki-manhattan-random.trycloudflare.com"
=======
client_id = "a08ea8f60487001c5975af2c84073f3c"
name = "Sticky-Cart-Bar"
handle = "sticky-cart-bar"
application_url = "https://hoped-north-toolkit-maritime.trycloudflare.com"
>>>>>>> f79bf3e24eb7a8c1a6bede0b753ef3095b0815af
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sticky-cart-bar.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
<<<<<<< HEAD
  "https://suspended-suzuki-manhattan-random.trycloudflare.com/auth/callback",
  "https://suspended-suzuki-manhattan-random.trycloudflare.com/auth/shopify/callback",
  "https://suspended-suzuki-manhattan-random.trycloudflare.com/api/auth/callback"
=======
  "https://hoped-north-toolkit-maritime.trycloudflare.com/auth/callback",
  "https://hoped-north-toolkit-maritime.trycloudflare.com/auth/shopify/callback",
  "https://hoped-north-toolkit-maritime.trycloudflare.com/api/auth/callback"
>>>>>>> f79bf3e24eb7a8c1a6bede0b753ef3095b0815af
]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://walrus-app-2gy22.ondigitalocean.app/api/webhooks"
  customer_data_request_url = "https://walrus-app-2gy22.ondigitalocean.app/api/webhooks"
  shop_deletion_url = "https://walrus-app-2gy22.ondigitalocean.app/api/webhooks"

[pos]
embedded = false
