# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0d8d8a4a2a6955698c50a2a1a881e05e"
name = "Sticky-cart-bar"
handle = "sticky-cart-bar-8"
application_url = "https://determination-del-fixtures-individuals.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sticky-cart-bar.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://determination-del-fixtures-individuals.trycloudflare.com/auth/callback",
  "https://determination-del-fixtures-individuals.trycloudflare.com/auth/shopify/callback",
  "https://determination-del-fixtures-individuals.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
