# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f83f18f42228f0ddffb9066f498469c5"
name = "Sticky-bar"
handle = "sticky-bar-7"
application_url = "https://letters-click-park-uploaded.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-demosky.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://letters-click-park-uploaded.trycloudflare.com/auth/callback",
  "https://letters-click-park-uploaded.trycloudflare.com/auth/shopify/callback",
  "https://letters-click-park-uploaded.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
