# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fd0a4ff5f240ff1d529a1ef467807cfa"
name = "Sticky-cart-bar"
handle = "sticky-cart-bar-7"
application_url = "https://move-strings-today-assembled.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "storeapp-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://move-strings-today-assembled.trycloudflare.com/auth/callback",
  "https://move-strings-today-assembled.trycloudflare.com/auth/shopify/callback",
  "https://move-strings-today-assembled.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
