# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "df80c5f38fd99dab5e78fa296c50a38d"
name = "subscription-app"
handle = "subscription-app-142"
application_url = "https://dude-paragraphs-row-hygiene.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-demosky.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://dude-paragraphs-row-hygiene.trycloudflare.com/auth/callback",
  "https://dude-paragraphs-row-hygiene.trycloudflare.com/auth/shopify/callback",
  "https://dude-paragraphs-row-hygiene.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
